- name: install aws cli 2
  shell: "curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip' && \
          unzip awscliv2.zip &&
          ./aws/install"
  ignore_errors: yes
