- name: install aws cli 2 step 1
  shell: "curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o '/tmp/awscliv2.zip'"
  ignore_errors: yes
  become: true

- name: install aws cli 2 step 2
  shell:  "unzip -o /tmp/awscliv2.zip -d /tmp/"
  ignore_errors: yes
  become: true

- name: install aws cli 2 step 3
  shell: "/tmp/aws/install"
  ignore_errors: yes
  become: true
