- name: Install nvm in zsh
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38/install.sh | zsh

- name: Install node in zsh
  shell: source ~/.zshrc && nvm install node
  args:
    executable: /bin/zsh
    warn: no
  become: false
   
- name: Install npm in zsh
  shell: source ~/.zshrc && nvm install-latest-npm
  args:
   executable: /bin/zsh
   warn: no
  become: false  

- name: Install nvm in bash
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38/install.sh | bash

- name: Install "pyright" package globally.
  npm:
    name: pyright
    global: yes
  become: true

- name: Install "intelephense" package globally.
  npm:
    name:  intelephense
    global: yes
  become: true

- name: Install "dockerfile-language-server-nodejs" package globally.
  npm:
    name: dockerfile-language-server-nodejs
    global: yes
  become: true

- name: Install "vim-language-server" package globally.
  npm:
    name: vim-language-server
    global: yes
  become: true

- name: Install "vscode-langservers-extracted" package globally.
  npm:
    name:  vscode-langservers-extracted
    global: yes
  become: true

- name: Install "dockly" package globally.
  npm:
    name: dockly
    global: yes
  become: true

- name: Install "fkill-cli" package globally.
  npm:
    name: fkill-cli
    global: yes
  become: true
    
- name: Install "bash-language-server" package globally.
  npm:
    name: bash-language-server
    global: yes
  become: true

- name: Install "vscode-css-languageserver-bin" package globally.
  npm:
    name: vscode-css-languageserver-bin
    global: yes
  become: true

- name: Install "vscode-html-languageserver-bin" package globally.
  npm:
    name: vscode-html-languageserver-bin
    global: yes
  become: true

- name: Install "javascript-typescript-langserver" package globally.
  npm:
    name: javascript-typescript-langserver
    global: yes
  become: true

  
- name: Install node version manager
  get_url:
      url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh
      dest: /tmp/nvm-installer.sh
      mode: +x
  become: false

- name: Execute the nvm-installer.sh
  shell: /tmp/nvm-installer.sh
  args:
    executable: /bin/zsh
  become: false

- name: Remove the nvm-installer.sh
  file: path=/tmp/nvm-installer.sh state=absent
  become: false
