 
---
- include: gh-cli.yml
- include: apt.yml
- include: zsh.yml
- include: docker.yml
- include: jenv.yml
- include: snap.yml
- include: kubernetes.yml
- include: zoxide.yml
- include: npm.yml
- include: brew.yml
- include: serverless.yml
- include: terraform.yml  
- include: pip.yml
- include: sdkman.yml 
- include: nvim.yml
- include: aws.yml
- include: nnn.yml
- include: grv.yml
- include: code.yml
    
  
