 
---
- include_tasks: nix.xml
- include_tasks: apt.yml
- include_tasks: zsh.yml
- include_tasks: docker.yml
- include_tasks: jenv.yml
- include_tasks: kubebox.yml
- include_tasks: npm.yml
- include_tasks: brew.yml
- include_tasks: pip.yml
- include_tasks: sdkman.yml 
- include_tasks: nvim.yml
- include_tasks: nnn.yml
- include_tasks: grv.yml

  
